# action.yml
name: 'Build Docker Image'
description: 'build and push a docker image'
inputs:
  dockerfile:
    description: 'dockerfile'
    default: '/GenericDockerfileForGo'
    required: true
  github_user:
    description: 'github_user'
    required: true
  github_token:
    description: 'github_token'
    required: true
  project:
    description: 'project'
    default: 'sk-private-registry/skysoft-atm'
    required: true
  gosec_opts:
    description: 'options for gosec command line'
    default: ''
    required: true
  skip_govet:
    description: 'option to skip go vet'
    default: 'false'
    required: true
  skip_staticcheck:
    description: 'option to skip staticcheck'
    default: 'false'
    required: true
  skip_gosec:
    description: 'option to skip gosec'
    default: 'false'
    required: true
  skip_golangci_lint:
    description: 'option to skip golangci-lint'
    default: 'false'
    required: true
  skip_tests:
    description: 'option to skip unit tests'
    default: 'false'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dockerfile }}
    - ${{ inputs.github_user }}
    - ${{ inputs.github_token }}
    - ${{ inputs.project }}
    - ${{ inputs.gosec_opts }}
    - ${{ inputs.skip_govet }}
    - ${{ inputs.skip_staticcheck }}
    - ${{ inputs.skip_gosec }}
    - ${{ inputs.skip_tests }}
    - ${{ inputs.skip_golangci_lint }}
